### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Softsapiens** [Rydgel/flappy-haskell#1]
Hi,
I'm using OSX, and I have installed sdl2, sdl2_mixer and sdl2_image with homebrew.

After that, I have cloned your repo with --recursive option to get submodules.

The problem appears during stack build:

:~/Code/haskell/flappy-haskell (master)$ stack build
sdl2-image-0.2: unregistering (local file changes: example/Example.hs src/SDL/ExceptionHelper.hs src/SDL/Image.hs src/SDL/Raw/Helper.hs src/SDL/Raw/...)
sdl2-image-0.2: configure
sdl2-image-0.2: build
sdl2-mixer-0.1: configure
sdl2-mixer-0.1: build
sdl2-image-0.2: install
Progress: 2/3
--  While building package sdl2-mixer-0.1 using:
      /Users/dani/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-osx-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ build lib:sdl2-mixer exe:sdl2-mixer-basic exe:sdl2-mixer-effect exe:sdl2-mixer-jumbled exe:sdl2-mixer-music exe:sdl2-mixer-raw --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/dani/Code/haskell/flappy-haskell/.stack-work/logs/sdl2-mixer-0.1.log

```
Configuring sdl2-mixer-0.1...
Preprocessing library sdl2-mixer-0.1...
[1 of 4] Compiling SDL.Raw.Helper   ( src/SDL/Raw/Helper.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/SDL/Raw/Helper.o )
[2 of 4] Compiling SDL.Raw.Mixer    ( .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/SDL/Raw/Mixer.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/SDL/Raw/Mixer.o )
[3 of 4] Compiling SDL.ExceptionHelper ( src/SDL/ExceptionHelper.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/SDL/ExceptionHelper.o )
[4 of 4] Compiling SDL.Mixer        ( src/SDL/Mixer.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/SDL/Mixer.o )

cbits/helpers.c:1:10:  fatal error: 'SDL2/SDL.h' file not found
#include "SDL2/SDL.h"
         ^
1 error generated.
```

Please, could you give me some advice in order to solve it?
Thanks in advance

**Comment by Rydgel** [comment]
@Softsapiens I've had this issue.
In my case it was something I forget to install with XCode.

This command:

```
xcode-select --install 
```

Fixed that issue for me.

**Comment by Softsapiens** [comment]
Yes!!! Build succesful!! you are right

I saw your tuit, but I don't get it :-)
Don't know that tool...

Now the problem is in execution... seems that my SDL mixer not has Ogg support...

$> stack exec flappy-haskell
flappy-haskell: SDLCallFailed {sdlExceptionCaller = "SDL.Mixer.initialize", sdlFunction = "Mix_Init", sdlExceptionError = "Mixer not built with Ogg Vorbis support"}

Thanks a lot!!

**Comment by Rydgel** [comment]
I think there is an option with Homebrew when compiling SDL2_Mixer to force the Ogg Vorbis support to be present.

**Comment by luigy** [comment]
this should do it `brew reinstall sdl2_mixer --with-libvorbis` and maybe a `stack clean` as well just in case?

@Rydgel any objections in dropping submodules in favor of stack git support? I can submit a PR

**Comment by Softsapiens** [comment]
Your are right again!

brew install sdl2_mixer --with-libvorbis

Thanks, I'm playing now... I will study your code for sure, thanks for sharing!

**Comment by Rydgel** [comment]
Thanks buddy.

**Comment by Rydgel** [comment]
@luigy: I didn't know stack could do this too. I don't have objections! Feel free to submit a PR.

**Comment by Softsapiens** [comment]
@luigy: thanks, I don't see the comment in time :-)   and good suggestion

**Comment by FranklinChen** [comment]
Maybe add these Homebrew steps to the README in a note for Mac OS X, since I reinvented the wheel needlessly before thinking of looking for an issue before filing one.

```
$ brew install sdl2 sdl2_image
$ brew install sdl2_mixer --with-libvorbis
```

And to the main README to make things complete:

```
$ git clone --recursive https://github.com/Rydgel/flappy-haskell
```

**Comment by Rydgel** [comment]
@FranklinChen done.
